"""Produce immutable source links and checksums for the blog's evidence index."""
import hashlib,json,sys
from pathlib import Path
root=Path(sys.argv[1]).resolve(); out=Path(__file__).resolve().parent
pin=json.loads((out/'snapshot.json').read_text())['commit']
# id, path, first relevant symbol/text
items=[
('readme','README.md','# Ruflo'),('package','package.json','"name"'),('wrapper','ruflo/bin/ruflo.js','function findCliPath'),('ruflo-package','ruflo/package.json','"dependencies"'),('cli-package','v3/@claude-flow/cli/package.json','"name"'),('cargo','Cargo.toml','[workspace]'),
('init','v3/@claude-flow/cli/src/init/executor.ts','export async function executeInit'),('settings','v3/@claude-flow/cli/src/init/settings-generator.ts','function generateHooksConfig'),('helpers','v3/@claude-flow/cli/src/init/helpers-generator.ts','export function generateAgentRouter'),('hook','v3/@claude-flow/cli/.claude/helpers/hook-handler.cjs','const handlers'),('dogfood-intelligence','.claude/helpers/intelligence.cjs','function getContext'),('agent-definition','.claude/agents/core/coder.md','name: coder'),('mcp-config','v3/@claude-flow/cli/src/init/mcp-generator.ts','export function generateMCPConfig'),('plugin-mcp','plugins/ruflo-core/.mcp.json','mcpServers'),
('mcp-entry','v3/@claude-flow/cli/bin/cli.js','const isMCPMode'),('mcp-client','v3/@claude-flow/cli/src/mcp-client.ts','export async function callMCPTool'),('tool-registry','v3/@claude-flow/mcp/src/tool-registry.ts','export class ToolRegistry'),('mcp-server','v3/@claude-flow/cli/src/mcp-server.ts','import'),('validation','v3/@claude-flow/cli-core/src/mcp-tools/validate-input.ts','export function validateIdentifier'),
('agent-tools','v3/@claude-flow/cli/src/mcp-tools/agent-tools.ts',"name: 'agent_spawn'"),('agent-execute','v3/@claude-flow/cli/src/mcp-tools/agent-execute-core.ts','export async function executeAgentTask'),('provider-call','v3/@claude-flow/cli/src/mcp-tools/agent-execute-core.ts','export async function callAnthropicMessages'),('swarm-tools','v3/@claude-flow/cli/src/mcp-tools/swarm-tools.ts',"name: 'swarm_init'"),('coordinator','v3/@claude-flow/swarm/src/unified-coordinator.ts','export class UnifiedSwarmCoordinator'),('assignment','v3/@claude-flow/swarm/src/unified-coordinator.ts','private async assignTask'),('queen','v3/@claude-flow/swarm/src/queen-coordinator.ts','private decomposeTask'),('transport','v3/@claude-flow/swarm/src/consensus/transport.ts','export interface ConsensusTransport'),('federation-transport','v3/@claude-flow/swarm/src/consensus/federation-transport.ts','import'),('workflow','v3/@claude-flow/cli/src/mcp-tools/workflow-tools.ts',"name: 'workflow_execute'"),('workflow-resume','v3/@claude-flow/cli/src/mcp-tools/workflow-tools.ts',"name: 'workflow_resume'"),
('memory-init','v3/@claude-flow/cli/src/memory/memory-initializer.ts','export async function initializeMemoryDatabase'),('memory-search','v3/@claude-flow/cli/src/memory/memory-initializer.ts','export async function searchEntries'),('memory-bridge','v3/@claude-flow/cli/src/memory/memory-bridge.ts','export async function bridgeSearchEntries'),('embedding','v3/@claude-flow/cli/src/memory/memory-initializer.ts','export async function generateLocalEmbedding'),('embedding-policy','v3/@claude-flow/cli/src/memory/embedding-policy.ts','export function requireRealEmbeddings'),('hybrid','v3/@claude-flow/cli/src/memory/hybrid-retrieval.ts','export function tokenize'),('smart','v3/@claude-flow/memory/src/smart-retrieval.ts','export interface SearchCandidate'),('memory-command','v3/@claude-flow/cli/src/commands/memory.ts','smartSearch'),('router','v3/@claude-flow/cli/src/ruvector/model-router.ts','Intelligent Model Router'),('intelligence','v3/@claude-flow/cli/src/memory/intelligence.ts','class LocalSonaCoordinator'),('lora','v3/@claude-flow/cli/src/ruvector/lora-adapter.ts','export const INPUT_DIM'),
('federation','v3/@claude-flow/plugin-agent-federation/src/application/federation-coordinator.ts','async sendMessage'),('federation-route','v3/@claude-flow/plugin-agent-federation/src/domain/services/routing-service.ts','async send'),('inbound','v3/@claude-flow/plugin-agent-federation/src/application/inbound-dispatcher.ts','export type InboundRejectionReason'),('trust','v3/@claude-flow/plugin-agent-federation/src/application/trust-evaluator.ts','computeScore'),('policy','v3/@claude-flow/cli/src/services/policy-runtime.ts','export async function authorizeMcpTool'),('policy-engine','v3/@claude-flow/security/src/policy/engine.ts','createLegacyCompatibleState'),
('codex-init','v3/@claude-flow/codex/src/initializer.ts','export class CodexInitializer'),('dual','v3/@claude-flow/codex/src/dual-mode/orchestrator.ts','async spawnWorker'),('codex-loop','v3/@claude-flow/codex/src/loop/index.ts','async function runCodexExec'),('wasm','v3/@claude-flow/cli/src/mcp-tools/wasm-agent-tools.ts','const SAFE_MCP_TOOLS'),('managed','v3/@claude-flow/cli/src/mcp-tools/managed-agent-tools.ts','import'),
]
records=[]
for key,path,symbol in items:
 data=(root/path).read_bytes();lines=data.decode().splitlines();line=next((i+1 for i,s in enumerate(lines) if symbol in s),None)
 if line is None: raise ValueError((path,symbol))
 records.append({'id':key,'path':path,'line':line,'symbol':symbol,'sha256':hashlib.sha256(data).hexdigest(),'url':f'https://github.com/ruvnet/ruflo/blob/{pin}/{path}#L{line}'})
(out/'source-inventory.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n')
(out/'source-links.md').write_text('\n'.join(f'[{r["id"]}]: {r["url"]}' for r in records)+'\n')
(out/'sources.md').write_text('# 源码证据索引\n\n所有链接锁定提交 `'+pin+'`，行号指向分析入口。SHA-256 见 [机器可读清单](source-inventory.json)。\n\n| 引用标识 | 源码入口 |\n| --- | --- |\n'+'\n'.join(f'| `{r["id"]}` | [{r["path"]}:{r["line"]}]({r["url"]}) |' for r in records)+'\n')
print(len(records),'source anchors verified')
